// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhxBf2ghqHbZpIjE1p1vAXHPauyjUZNs',
    appId: '1:688022961489:web:4acdb3b7c928f57494a770',
    messagingSenderId: '688022961489',
    projectId: 'test-cli-d58f3',
    authDomain: 'test-cli-d58f3.firebaseapp.com',
    storageBucket: 'test-cli-d58f3.appspot.com',
    measurementId: 'G-Q6LGMFDMD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBXEbsxh4viUvjV07C7DAt9q8L80IjZ8',
    appId: '1:688022961489:android:3a06aa09bdaf2f3f94a770',
    messagingSenderId: '688022961489',
    projectId: 'test-cli-d58f3',
    storageBucket: 'test-cli-d58f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6Qk6-CAZtmsP1JK5qkRK43RIE7eTMCU',
    appId: '1:688022961489:ios:0d021f54a132714e94a770',
    messagingSenderId: '688022961489',
    projectId: 'test-cli-d58f3',
    storageBucket: 'test-cli-d58f3.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6Qk6-CAZtmsP1JK5qkRK43RIE7eTMCU',
    appId: '1:688022961489:ios:845edd07dd701f8994a770',
    messagingSenderId: '688022961489',
    projectId: 'test-cli-d58f3',
    storageBucket: 'test-cli-d58f3.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
